### ISSUE TITLE
Please someone make an API without guzzle

### ISSUE THREAD

**Issue by andreysneg** [scheb/yahoo-finance-api#53]
Without guzzle library dont work.

Guzzle is difficult to set and study.

Please someone make an API without guzzle

**Comment by scheb** [comment]
I do not understand the problem, because if you install via Composer and you use `ApiClientFactory::createApiClient()` to initialize the API client, you don't even get in touch with Guzzle 🤷

This library will continue to use Guzzle, which one of the most well-built in reliable HTTP clients in the PHP ecosystem. If you dislike this decision, feel free to fork and make the adjustments you need.
